services:
  db:
    image: postgres:15-alpine
    container_name: fame_academy_quest_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - fame_academy_quest_db_data:/var/lib/postgresql/data

volumes:
  fame_academy_quest_db_data: