default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>


development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>
production:
  primary: &primary_production
    <<: *default
    database: fame_academy_quest_production
    username: fame_academy_quest
    password: <%= ENV["FAME_ACADEMY_QUEST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fame_academy_quest_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fame_academy_quest_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fame_academy_quest_production_cable
    migrations_paths: db/cable_migrate
