default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: fame_academy_quest_development
test:
  <<: *default
  database: fame_academy_quest_test
production:
  primary: &primary_production
    <<: *default
    database: fame_academy_quest_production
    username: fame_academy_quest
    password: <%= ENV["FAME_ACADEMY_QUEST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fame_academy_quest_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fame_academy_quest_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fame_academy_quest_production_cable
    migrations_paths: db/cable_migrate
